service: optin-api

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: user
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: user/{id}
          method: get
          cors: true
  getUserByPhone:
    handler: handler.getUserByPhone
    events:
      - http:
          path: user/phone/{phone}
          method: get
          cors: true
  getAll:
    handler: handler.getAll
    events:
     - http:
         path: users
         method: get
         cors: true
  update:
    handler: handler.update
    events:
     - http:
         path: user/{id}
         method: put
         cors: true
  optin:
    handler: handler.optin
    events:
     - http:
         path: user/optin/{phone}
         method: put
         cors: true
  optout:
    handler: handler.optout
    events:
     - http:
         path: user/optout/{phone}
         method: put
         cors: true
  delete:
    handler: handler.delete
    events:
     - http:
         path: user/{id}
         method: delete
         cors: true

# plugins:
# - serverless-offline
