service: users-api

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  stage: ${opt:stage, self:provider.stage}
  environment:
    DB: ${env:DB_CONNECTION_STRING}

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1

functions:
  createUser:
    handler: api/create.newUser
    events:
      - http:
          path: api/user
          method: post
          cors: true
  getOne:
    handler: api/get.getOne
    events:
      - http:
          path: api/user/{id}
          method: get
          cors: true
  getUserByPhone:
    handler: api/get.getUserByPhone
    events:
      - http:
          path: api/phone/{phone}
          method: get
          cors: true
  getAll:
    handler: api/get.getAllUsers
    events:
     - http:
         path: api/users
         method: get
         cors: true
  updateById:
    handler: api/update.byId
    events:
     - http:
         path: api/user/{id}
         method: put
         cors: true
  updateConsent:
    handler: api/update.consentByPhone
    events:
     - http:
         path: api/consent/{phone}
         method: put
         cors: true
  deleteById:
    handler: api/delete.removeById
    events:
     - http:
         path: api/user/{id}
         method: delete
         cors: true
